# Generated by Django 3.0.5 on 2020-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_as',
            field=models.CharField(blank=True, choices=[('Doc', 'Doctor'), ('Patnt', 'Patient')], max_length=20),
        ),
    ]
