# Generated by Django 3.0.5 on 2020-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_registered_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='case_paper',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registered_as',
            field=models.CharField(choices=[('', 'Choose...'), ('Doc', 'Doctor'), ('Patnt', 'Patient')], max_length=20),
        ),
    ]
