# Generated by Django 3.0.5 on 2020-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200523_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='case_paper',
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('', 'Choose...'), ('A', 'A'), ('A+', 'A+'), ('B', 'B'), ('B+', 'B+'), ('O+', 'O+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
    ]
