# Generated by Django 3.0.5 on 2020-05-25 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescreption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=50)),
                ('prescreption', models.TextField(max_length=500)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescribed', to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
