# Generated by Django 3.0.5 on 2020-05-25 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_prescreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreption',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
