# Generated by Django 3.0.5 on 2020-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding', models.IntegerField(blank=True)),
                ('paid', models.IntegerField(blank=True)),
                ('medical_rec', models.ImageField(blank=True, default='default.jpg', upload_to='medical_records')),
                ('case_paper', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
