# Generated by Django 3.0.5 on 2020-05-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
